version: "2.3"
services:
  db:
    image: mysql:latest
    volumes:
    - type: bind
      source: ./database
      target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vending_machine_db
      - MYSQL_USER=machine
      - MYSQL_PASSWORD=machine
    ports:
    - 3306:3306

  web:
#    build: ./src/Docker
    image: vending-machine_image
    depends_on:
      - db
    ports:
    - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=machine
      - DATABASE_PASSWORD=machine
      - DATABASE_NAME=vending_machine_db
      - DATABASE_PORT=3306
